import Eden

#print axioms Eden.q_expansion
#print axioms Eden.tangentialRate_eq_q
#print axioms Eden.radialRate_eq_q_add
#print axioms Eden.radialRate_add_four
#print axioms Eden.tangentialRate_add_two
#print axioms Eden.rates_sum
#print axioms Eden.radialRate_lower_bound
#print axioms Eden.tangentialRate_lower_bound
#print axioms Eden.tangentialRate_nonneg
#print axioms Eden.rates_at_stationary_radii
#print axioms Eden.total_rate_identity
#print axioms Eden.total_rate_le
#print axioms Eden.total_rate_neg
#print axioms Eden.targetDimension_bounds
#print axioms Eden.targetDimension_eight
#print axioms Eden.radiusEvolution_eq_amplitude
#print axioms Eden.planar_evolution_polar
#print axioms Eden.exists_initial_polar_angle
#print axioms Eden.exists_planar_angular_lift
#print axioms Eden.discScale_radius_bound
#print axioms Eden.discScale_distance_sq
#print axioms Eden.attractorProjection_mem
#print axioms Eden.dist_attractorProjection_sq
#print axioms Eden.infDist_attractor_sq_le
#print axioms Eden.fderiv_planarX_apply
#print axioms Eden.fderiv_planarY_apply
#print axioms Eden.fderiv_evolution_apply
#print axioms Eden.exists_positive_rotation_between
#print axioms Eden.exists_planar_time_on_stationary_radius
#print axioms Eden.firstCircle_invariant
#print axioms Eden.secondCircle_invariant
#print axioms Eden.forwardOrbit_eq_firstCircle
#print axioms Eden.forwardOrbit_eq_secondCircle
#print axioms Eden.commonIndexCandidates_isLeast
#print axioms Eden.commonIndex_eq_four
#print axioms Eden.commonIndexRatio_eq
#print axioms Eden.commonIndexLocalDimension_eq
#print axioms Eden.commonIndexRatio_isGreatest
#print axioms Eden.commonIndexDimension_eq_target
#print axioms Eden.commonIndexLocalDimension_eq_target_iff
#print axioms Eden.commonIndexLocalDimension_isGreatest
#print axioms Eden.exponentSum_four_unit_circle
#print axioms Eden.exponentSum_four_outer_circle
#print axioms Eden.exponentSum_four_origin
#print axioms Eden.exponentSum_four_periodic_le
#print axioms Eden.exponentSum_four_periodic_isGreatest
#print axioms Eden.commonIndexLocalDimension_periodic_isGreatest
#print axioms Eden.supremum_commonIndexLocalDimension_periodic
#print axioms Eden.commonIndex_periodic_gap
#print axioms Eden.periodic_dimension_conventions_distinct
#print axioms Eden.amplitudeSq_pos_on_interval
#print axioms Eden.squaredRadiusEvolution_mem_lower_interval
#print axioms Eden.squaredRadiusEvolution_mem_upper_interval
#print axioms Eden.hasDerivAt_evolution_of_mem_attractor
#print axioms Eden.radiusSq₁_evolution_all_time
#print axioms Eden.radiusSq₂_evolution_all_time
#print axioms Eden.evolution_mem_attractor_all_time
#print axioms Eden.exists_complete_solution_in_attractor
#print axioms Eden.radiusEvolution_mem_lower_interval
#print axioms Eden.radiusEvolution_mem_upper_interval
#print axioms Eden.hasDerivAt_radiusEvolution_all_time
#print axioms Eden.diagonalLinear_apply
#print axioms Eden.derivativeFactors_pos
#print axioms Eden.fderiv_evolution_radialFrame
#print axioms Eden.fderiv_evolution_orthogonal_decomposition
#print axioms Eden.diagonalLinear_bijective
#print axioms Eden.fderiv_evolution_bijective
#print axioms Eden.radialCos_sq_add_radialSin_sq
#print axioms Eden.radius_mul_radialCos
#print axioms Eden.radius_mul_radialSin
#print axioms Eden.planarDerivativeX_on_radialFrame
#print axioms Eden.planarDerivativeY_on_radialFrame
#print axioms Eden.tendsto_finiteTimeDimension_of_asymptotic_zero
#print axioms Eden.tendsto_finiteTimeDimension_of_spectrum_pos
#print axioms Eden.tendsto_finiteTimeDimension
#print axioms Eden.tendsto_spectrumInterpolation_normalized
#print axioms Eden.eventually_finiteTimeDimension_lt
#print axioms Eden.tendsto_finiteTimeDimension_of_lower_tests
#print axioms Eden.tendsto_finiteTimeDimension_of_interpolation_pos
#print axioms Eden.tendsto_finiteTimeDimension_of_eventual_lower_bound
#print axioms Eden.kaplanYorkeDimension_zero_zero
#print axioms Eden.kaplanYorkeDimension_zero_one
#print axioms Eden.kaplanYorkeDimension_zero_two
#print axioms Eden.kaplanYorkeDimension_one_one
#print axioms Eden.kaplanYorkeDimension_one_two
#print axioms Eden.kaplanYorkeDimension_two_two
#print axioms Eden.kaplanYorkeDimension_radiusPair_bound_and_eq
#print axioms Eden.asymptoticDimension_le_target
#print axioms Eden.asymptoticDimension_eq_target_iff_radii
#print axioms Eden.asymptoticDimension_eq_target_iff
#print axioms Eden.asymptoticDimension_lt_target_of_not_mem_torus
#print axioms Eden.asymptoticDimension_on_torus
#print axioms Eden.asymptoticDimension_attractor_isGreatest
#print axioms Eden.supremum_asymptoticDimension_attractor
#print axioms Eden.globalLyapunovDimension_eq_supremum_asymptoticDimension
#print axioms Eden.divergence_eq_rates
#print axioms Eden.divergence_eq
#print axioms Eden.divergence_le
#print axioms Eden.divergence_neg
#print axioms Eden.spectrumInterpolation_kaplanYorke_eq_zero
#print axioms Eden.tendsto_spectrumPartialSum_normalized
#print axioms Eden.kaplanYorkeIndex_eq_of_adjacent_signs
#print axioms Eden.eventually_dimension_zero_of_first_exponent_neg
#print axioms Eden.eventually_dimension_zero_of_limiting_radii
#print axioms Eden.normalized_nonneg_of_factor_subset
#print axioms Eden.normalized_first_nonneg_of_radius
#print axioms Eden.normalized_first_two_nonneg_of_radii
#print axioms Eden.eventually_dimension_formula_of_neutral_prefix
#print axioms Eden.tangentialRate_along_nonneg
#print axioms Eden.finiteTimeDimension_of_limiting_unit_radii
#print axioms Eden.eventually_dimension_formula_zero_two
#print axioms Eden.eventually_dimension_formula_two_two
#print axioms Eden.evolution_zero_time
#print axioms Eden.hasDerivAt_euclidean_of_coord
#print axioms Eden.hasDerivAt_evolution
#print axioms Eden.exists_global_forward_solution
#print axioms Eden.contDiff_vectorField
#print axioms Eden.supremumSingularProduct_four_five
#print axioms Eden.globalLogGrowth_four
#print axioms Eden.globalLogGrowth_five
#print axioms Eden.globalGrowthRate_four
#print axioms Eden.globalGrowthRate_five
#print axioms Eden.globalLogGrowth_index_zero
#print axioms Eden.globalGrowthRate_zero
#print axioms Eden.singularValueFunction_torus_integer_ge_one
#print axioms Eden.globalLogGrowth_nonneg
#print axioms Eden.globalGrowthRate_nonneg
#print axioms Eden.globalGrowthRate_five_neg
#print axioms Eden.lyapunovExponent_bounds
#print axioms Eden.lyapunovExponent_fifth
#print axioms Eden.exponentSum_four_bound_and_eq
#print axioms Eden.exponentSum_four_eq_iff
#print axioms Eden.exponentSum_five
#print axioms Eden.exponentSum_on_torus
#print axioms Eden.exponentSum_le_twice_index
#print axioms Eden.exponentSum_image_bddAbove
#print axioms Eden.exponentSum_four_isGreatest
#print axioms Eden.exponentSum_five_isGreatest
#print axioms Eden.supremumExponentSum_four
#print axioms Eden.supremumExponentSum_five
#print axioms Eden.supremumExponentSum_nonneg
#print axioms Eden.exteriorOperator_comp
#print axioms Eden.singularValueFunction_integer_comp_le
#print axioms Eden.fderiv_evolution_add
#print axioms Eden.singularValueFunction_evolution_add_le
#print axioms Eden.singularValueFunction_integer_evolution_pos
#print axioms Eden.singularValueFunction_integer_evolution_zero
#print axioms Eden.exteriorBasis_apply
#print axioms Eden.diagonalLinear_basis
#print axioms Eden.exterior_map_diagonal_basis
#print axioms Eden.norm_exterior_map_isometry
#print axioms Eden.exterior_map_diagonal_repr
#print axioms Eden.norm_sq_exterior_map_diagonal
#print axioms Eden.norm_sq_exteriorEvolution
#print axioms Eden.exteriorInitialCoordinates_ne_zero
#print axioms Eden.inner_exterior_map_gram
#print axioms Eden.singularExteriorBasis_apply
#print axioms Eden.selectedSingularProduct_nonneg
#print axioms Eden.selectedSingularProduct_eq_prod
#print axioms Eden.gram_singularVectorBasis
#print axioms Eden.exterior_gram_basis
#print axioms Eden.norm_sq_exterior_map_singular_basis
#print axioms Eden.exteriorSupport_nonempty
#print axioms Eden.exteriorFactor_pos
#print axioms Eden.tendsto_log_exteriorFactor_div
#print axioms Eden.norm_sq_exteriorEvolution_support
#print axioms Eden.tendsto_log_exterior_coordinate_sq_div
#print axioms Eden.tendsto_log_norm_exteriorEvolution_div
#print axioms Eden.exteriorGrowthRate_eq
#print axioms Eden.tendsto_exteriorGrowthRate
#print axioms Eden.limsup_exteriorGrowthRate
#print axioms Eden.norm_initialExteriorBasisVector
#print axioms Eden.initialExteriorBasisVector_ne_zero
#print axioms Eden.exteriorInitialCoordinates_basis
#print axioms Eden.exteriorSupport_basis
#print axioms Eden.exteriorGrowthRate_basis
#print axioms Eden.exteriorRate_eq_sum
#print axioms Eden.spectrumPartialSum_eq_fin_sum
#print axioms Eden.isGreatest_exteriorRate
#print axioms Eden.isGreatest_exteriorGrowthRate_unit
#print axioms Eden.isGreatest_exteriorGrowthRate_nonzero
#print axioms Eden.exteriorOperator_apply
#print axioms Eden.singularValueFunction_integer
#print axioms Eden.singularValueFunction_integer_eq_fin_prod
#print axioms Eden.exteriorFactor_eq_prod
#print axioms Eden.isGreatest_exteriorFactor
#print axioms Eden.norm_exteriorInitialCoordinates
#print axioms Eden.norm_exteriorEvolution_initialBasis
#print axioms Eden.norm_exteriorEvolution_le
#print axioms Eden.norm_exteriorOperator_evolution
#print axioms Eden.isGreatest_selectedSingularProduct
#print axioms Eden.norm_exterior_map_singular_basis
#print axioms Eden.norm_exterior_map_le_singularValueFunction
#print axioms Eden.norm_exteriorOperator_eq_singularValueFunction
#print axioms Eden.log_radialAmplitude_lower_bound
#print axioms Eden.log_planarAmplitude_lower_bound
#print axioms Eden.radialAmplitude_lower_bound
#print axioms Eden.planarAmplitude_lower_bound
#print axioms Eden.log_planarAmplitude_nonneg
#print axioms Eden.one_le_planarAmplitude
#print axioms Eden.derivativeFactors_ge_fifth
#print axioms Eden.singularValues_fderiv_evolution_fifth
#print axioms Eden.tendsto_squaredRadiusEvolution_all
#print axioms Eden.tendsto_log_radialAmplitude_div
#print axioms Eden.tendsto_log_planarAmplitude_div
#print axioms Eden.tendsto_radialRate_average
#print axioms Eden.tendsto_tangentialRate_average
#print axioms Eden.limiting_rates_of_lt_one
#print axioms Eden.limiting_rates_at_one
#print axioms Eden.limiting_rates_of_one_lt
#print axioms Eden.tendsto_log_derivativeFactors_div
#print axioms Eden.singularValueFunction_evolution_on_four_five
#print axioms Eden.singularValueFunction_evolution_at_target
#print axioms Eden.singularValueFunction_evolution_above_target
#print axioms Eden.singularValueFunction_evolution_above_target_lt_one
#print axioms Eden.finiteTimeDimension_le_target
#print axioms Eden.finiteTimeDimension_eq_target_iff
#print axioms Eden.finiteTimeDimension_lt_target_of_not_mem_torus
#print axioms Eden.finiteTimeDimension_on_torus
#print axioms Eden.finiteTimeDimension_attractor_isGreatest
#print axioms Eden.supremum_finiteTimeDimension_attractor
#print axioms Eden.globalLyapunovDimension_attractor
#print axioms Eden.globalLyapunovDimension_attractor_eight
#print axioms Eden.singularValueFunction_evolution_pos
#print axioms Eden.one_le_singularValueFunction_iff_interpolation
#print axioms Eden.admissibleDimensions_evolution_eq
#print axioms Eden.finiteTimeDimension_eq_kaplanYorke
#print axioms Eden.frequencyEvolution_image_attractor
#print axioms Eden.frequencyEvolution_mem_torus
#print axioms Eden.attractor_frequencyUniformlyAttractsBounded
#print axioms Eden.attractor_isFrequencyGlobalAttractor
#print axioms Eden.frequencyUniformlyAttractsBounded_nonempty
#print axioms Eden.frequency_attractor_minimal
#print axioms Eden.singularValueFunction_frequencyEvolution
#print axioms Eden.frequencyFiniteTimeDimension_eq
#print axioms Eden.frequencyGlobalLyapunovDimension_eq
#print axioms Eden.tendsto_frequencyLogSingularValue
#print axioms Eden.frequencyLyapunovExponent_eq
#print axioms Eden.tendsto_frequencyLyapunovExponent
#print axioms Eden.frequencyAsymptoticDimension_eq
#print axioms Eden.tendsto_frequencyFiniteTimeDimension
#print axioms Eden.frequencyFiniteTimeDimension_bound_and_eq
#print axioms Eden.frequencyAsymptoticDimension_bound_and_eq
#print axioms Eden.frequencyFiniteTimeDimension_isGreatest
#print axioms Eden.frequencyAsymptoticDimension_isGreatest
#print axioms Eden.frequencyGlobalLyapunovDimension_attractor
#print axioms Eden.frequencyVectorField_sqrt_two
#print axioms Eden.frequencyEvolution_sqrt_two
#print axioms Eden.frequencyEvolution_zero_time
#print axioms Eden.hasDerivAt_frequencyEvolution
#print axioms Eden.exists_frequency_global_forward_solution
#print axioms Eden.contDiff_frequencyVectorField
#print axioms Eden.radiusSq_frequencyEvolution
#print axioms Eden.frequencyEvolution_fifth
#print axioms Eden.frequencyEvolution_eq_correction
#print axioms Eden.radiusSq_frequencyCorrection
#print axioms Eden.frequencyCorrection_fifth
#print axioms Eden.frequencyCorrection_mem_attractor_iff
#print axioms Eden.frequencyCorrection_mem_torus_iff
#print axioms Eden.frequencyCorrection_image_attractor
#print axioms Eden.frequencyCorrection_image_torus
#print axioms Eden.contDiff_frequencyEvolution
#print axioms Eden.fderiv_frequencyEvolution
#print axioms Eden.fderiv_frequencyEvolution_orthogonal
#print axioms Eden.singularValues_fderiv_frequencyEvolution
#print axioms Eden.ordered_singularValues_frequencyEvolution
#print axioms Eden.singularValues_frequencyEvolution_eq
#print axioms Eden.fderiv_frequencyEvolution_bijective
#print axioms Eden.frequency_solution_unique_on_Icc
#print axioms Eden.continuousOn_frequencyEvolution
#print axioms Eden.frequencyEvolution_unique
#print axioms Eden.frequencyEvolution_add
#print axioms Eden.integerGrowthValues_nonempty
#print axioms Eden.integerGrowthValues_bddAbove
#print axioms Eden.supremumSingularProduct_bounds
#print axioms Eden.supremumSingularProduct_pos
#print axioms Eden.singularValueFunction_le_supremum
#print axioms Eden.supremumSingularProduct_zero
#print axioms Eden.globalLogGrowth_zero
#print axioms Eden.supremumSingularProduct_add_le
#print axioms Eden.globalLogGrowth_subadditive
#print axioms Eden.globalLogGrowth_bounds
#print axioms Eden.abs_globalLogGrowth_le
#print axioms Eden.exists_globalLogGrowth_linear_bound
#print axioms Eden.spectrumEntry_globalGrowthIncrements
#print axioms Eden.spectrumPartialSum_globalGrowthIncrements
#print axioms Eden.globalGrowthInterpolation_interpolate
#print axioms Eden.globalGrowthInterpolation_integer
#print axioms Eden.globalGrowthInterpolation_four_five
#print axioms Eden.globalGrowthIndex_eq_four
#print axioms Eden.globalGrowthInterpolation_isGreatest
#print axioms Eden.globalGrowthDimension_eq_target
#print axioms Eden.globalGrowthDimension_eq_rate_ratio
#print axioms Eden.tendsto_globalLogGrowth_div_inf
#print axioms Eden.globalGrowthRate_eq_inf
#print axioms Eden.tendsto_globalGrowthRate
#print axioms Eden.hasDerivAt_sqrt_radialDiscriminant
#print axioms Eden.hasDerivAt_radialAmplitude
#print axioms Eden.radialAmplitude_zero_time
#print axioms Eden.hasDerivAt_log_planarAmplitude
#print axioms Eden.hasDerivAt_log_radialAmplitude
#print axioms Eden.continuousOn_squaredRadiusEvolution_time
#print axioms Eden.log_planarAmplitude_eq_integral
#print axioms Eden.log_radialAmplitude_eq_integral
#print axioms Eden.planarAmplitude_eq_exp_integral
#print axioms Eden.radialAmplitude_eq_exp_integral
#print axioms Eden.dimH_attractor
#print axioms Eden.dimH_torus
#print axioms Eden.isOpen_euclideanOpenCube
#print axioms Eden.euclideanOpenCube_nonempty
#print axioms Eden.dimH_euclideanOpenCube
#print axioms Eden.projectFour_embedFour
#print axioms Eden.embedFour_projectFour
#print axioms Eden.attractor_subset_range_embedFour
#print axioms Eden.embedFour_mem_attractor
#print axioms Eden.euclideanOpenCube_subset_projectFour
#print axioms Eden.torusGraph_mem
#print axioms Eden.projectTorus_torusGraph
#print axioms Eden.euclideanOpenCube_subset_projectTorus
#print axioms Eden.range_torusParametrization
#print axioms Eden.contDiff_torusParametrization
#print axioms Eden.contDiff_amplitudeSq
#print axioms Eden.contDiffAt_planarAmplitude
#print axioms Eden.radialAmplitude_pos
#print axioms Eden.amplitudeSq_parameter_identity
#print axioms Eden.planarAmplitude_parameter_identity
#print axioms Eden.contDiff_evolution
#print axioms Eden.norm_planeProjection
#print axioms Eden.norm_planeProjection_le
#print axioms Eden.planeProjection_sub
#print axioms Eden.plane_radius_sub_le_dist
#print axioms Eden.one_sub_plane_radius_le_infDist
#print axioms Eden.norm_planeProjection_radialPerturbation
#print axioms Eden.radialPerturbation_mem_attractor
#print axioms Eden.dist_radialPerturbation
#print axioms Eden.plane_radius_evolution_radialPerturbation
#print axioms Eden.radialRate_upper_bound
#print axioms Eden.tangentialRate_upper_bound
#print axioms Eden.log_radialAmplitude_upper_bound
#print axioms Eden.log_planarAmplitude_upper_bound
#print axioms Eden.radialAmplitude_upper_bound
#print axioms Eden.planarAmplitude_upper_bound
#print axioms Eden.derivativeFactors_upper_bound
#print axioms Eden.singularValues_evolution_bounds
#print axioms Eden.singularValueFunction_integer_evolution_bounds
#print axioms Eden.spectrumInterpolation_eq_min_sum
#print axioms Eden.concaveOn_spectrumInterpolation
#print axioms Eden.concaveOn_log_singularValueFunction
#print axioms Eden.concaveOn_lyapunovExponent_interpolation
#print axioms Eden.spectrumEntry_antitone
#print axioms Eden.spectrumPartialSum_nonneg_of_le
#print axioms Eden.kaplanYorkeIndex_le_dimension
#print axioms Eden.kaplanYorkeDimension_lt_succ_index
#print axioms Eden.kaplanYorkeDimension_formula_of_index_lt_five
#print axioms Eden.spectrumInterpolation_index_criterion
#print axioms Eden.exists_dimension_segment
#print axioms Eden.spectrumInterpolation_nonneg_iff
#print axioms Eden.spectrumInterpolation_neg_iff
#print axioms Eden.radiusSq₁_nonneg
#print axioms Eden.radiusSq₂_nonneg
#print axioms Eden.continuous_radiusSq₁
#print axioms Eden.continuous_radiusSq₂
#print axioms Eden.radiusSq₁_evolution
#print axioms Eden.radiusSq₂_evolution
#print axioms Eden.evolution_mem_attractor
#print axioms Eden.evolution_mem_torus
#print axioms Eden.torus_subset_attractor
#print axioms Eden.isClosed_attractor
#print axioms Eden.isClosed_torus
#print axioms Eden.norm_sq_phaseSpace
#print axioms Eden.norm_le_two_of_mem_attractor
#print axioms Eden.isCompact_attractor
#print axioms Eden.isCompact_torus
#print axioms Eden.attractor_nonempty
#print axioms Eden.torus_nonempty
#print axioms Eden.contDiffAt_amplitudeSq_joint
#print axioms Eden.contDiffAt_planarAmplitude_joint
#print axioms Eden.contDiffAt_evolution_joint
#print axioms Eden.contDiffOn_evolution_joint
#print axioms Eden.spectrumPartialSum_zero
#print axioms Eden.spectrumPartialSum_succ
#print axioms Eden.nonnegativeSumIndices_nonempty
#print axioms Eden.kaplanYorkeIndex_mem
#print axioms Eden.le_kaplanYorkeIndex
#print axioms Eden.kaplanYorkeIndex_eq
#print axioms Eden.spectrumPartialSum_after_index_neg
#print axioms Eden.spectrumEntry_at_kaplanYorkeIndex_neg
#print axioms Eden.kaplanYorkeDimension_of_index_zero
#print axioms Eden.kaplanYorkeDimension_of_index_five
#print axioms Eden.kaplanYorkeDimension_of_index_between
#print axioms Eden.kaplanYorkeDimension_between_index
#print axioms Eden.kaplanYorkeDimension_mem_interval
#print axioms Eden.spectrumInterpolation_pos_zero_one
#print axioms Eden.spectrumInterpolation_pos_one_two
#print axioms Eden.spectrumInterpolation_pos_one_one
#print axioms Eden.one_lt_of_limitingSquaredRadius_eq_two
#print axioms Eden.singularWeight_bounds
#print axioms Eden.continuous_spectrumInterpolation
#print axioms Eden.spectrumInterpolation_eq_range
#print axioms Eden.spectrumInterpolation_interpolate
#print axioms Eden.spectrumInterpolation_zero
#print axioms Eden.spectrumInterpolation_five
#print axioms Eden.spectrumInterpolation_dist_le
#print axioms Eden.log_singularValueFunction_div_time
#print axioms Eden.tendstoUniformly_spectrumInterpolation
#print axioms Eden.tendstoUniformlyOn_log_singularValueFunction
#print axioms Eden.log_add_bounds
#print axioms Eden.tendsto_log_add_div
#print axioms Eden.tendsto_log_finset_sum_div
#print axioms Eden.singularValues_evolution_pos
#print axioms Eden.normalizedLogSingularValues_antitone
#print axioms Eden.normalizedLogSingularValues_eq_descending
#print axioms Eden.tendsto_normalizedLogSingularValues
#print axioms Eden.lyapunovExponent_eq_descending
#print axioms Eden.tendsto_lyapunovExponent
#print axioms Eden.lyapunovExponent_antitone
#print axioms Eden.multiset_lyapunovExponent
#print axioms Eden.nonneg_of_card_nonneg
#print axioms Eden.finiteTimeDimension_ge_of_nonneg_factor_count
#print axioms Eden.finiteTimeDimension_ge_one_of_tangential_factor
#print axioms Eden.finiteTimeDimension_ge_one_of_first_radius
#print axioms Eden.finiteTimeDimension_ge_one_of_second_radius
#print axioms Eden.finiteTimeDimension_ge_two_of_radii
#print axioms Eden.unstableRelativeTo_of_unit_plane_in
#print axioms Eden.unstableRelativeTo_of_unit_plane
#print axioms Eden.radialPerturbation_mem_coordinatePlane
#print axioms Eden.firstCircle_unstableInPlane
#print axioms Eden.secondCircle_unstableInPlane
#print axioms Eden.firstCircle_unstableRelativeTo
#print axioms Eden.secondCircle_unstableRelativeTo
#print axioms Eden.torus_unstableRelativeTo
#print axioms Eden.unstableRelativeTo_mono
#print axioms Eden.evolution_image_stationary_radii
#print axioms Eden.unit_sets_invariant_and_unstable
#print axioms Eden.mem_innerRadialRegion_iff_radius
#print axioms Eden.mem_outerRadialRegion_iff_radius
#print axioms Eden.mem_unitRadialLevel_iff_radius
#print axioms Eden.innerRadialRegion_nonempty
#print axioms Eden.outerRadialRegion_nonempty
#print axioms Eden.radialRegions_disjoint
#print axioms Eden.isOpen_innerRadialRegion
#print axioms Eden.isOpen_outerRadialRegion
#print axioms Eden.radiusSq₁_evolution_lt_one_iff
#print axioms Eden.one_lt_radiusSq₁_evolution_iff
#print axioms Eden.radiusSq₁_evolution_eq_one_iff
#print axioms Eden.evolution_image_innerRadialRegion
#print axioms Eden.evolution_image_outerRadialRegion
#print axioms Eden.evolution_image_unitRadialLevel
#print axioms Eden.evolution_inner_disjoint_outer
#print axioms Eden.attractor_not_subset_closure_forwardOrbit
#print axioms Eden.not_openSet_transitive_attractor
#print axioms Eden.antitone_eq_of_multiset_eq
#print axioms Eden.singularValues_on_torus
#print axioms Eden.singularValues_at_origin
#print axioms Eden.rotateBlocks_inverse
#print axioms Eden.norm_rotateBlocks
#print axioms Eden.blockRotation_apply
#print axioms Eden.log_planarAmplitude_div_of_stationary
#print axioms Eden.log_radialAmplitude_div_of_stationary
#print axioms Eden.limitingSquaredRadius_of_stationary
#print axioms Eden.normalizedLogSingularValues_of_stationary_radii
#print axioms Eden.normalizedLogSingularValues_eq_lyapunovExponent_of_stationary
#print axioms Eden.finiteTimeDimension_eq_asymptotic_on_periodic
#print axioms Eden.asymptoticDimension_at_origin
#print axioms Eden.asymptoticDimension_first_unit_circle
#print axioms Eden.asymptoticDimension_second_unit_circle
#print axioms Eden.asymptoticDimension_first_outer_circle
#print axioms Eden.asymptoticDimension_second_outer_circle
#print axioms Eden.normalizedLogSingularValues_unit_circle
#print axioms Eden.normalizedLogSingularValues_outer_circle
#print axioms Eden.finiteTimeDimension_at_origin
#print axioms Eden.asymptoticDimension_periodic_le_three
#print axioms Eden.asymptoticDimension_periodic_isGreatest
#print axioms Eden.finiteTimeDimension_periodic_isGreatest
#print axioms Eden.supremum_asymptoticDimension_periodic
#print axioms Eden.supremum_finiteTimeDimension_periodic
#print axioms Eden.periodic_asymptotic_dimension_gap
#print axioms Eden.periodic_finiteTime_dimension_gap
#print axioms Eden.dimension_gap_eight
#print axioms Eden.periodicGlobalGrowthIncrements_eq
#print axioms Eden.periodicGlobalGrowthInterpolation_eq
#print axioms Eden.periodicGlobalGrowthInterpolation_integer
#print axioms Eden.periodicGlobalGrowthInterpolation_interpolate
#print axioms Eden.periodicGlobalGrowthIndex_eq_three
#print axioms Eden.periodicGlobalGrowthInterpolation_isGreatest
#print axioms Eden.periodicGlobalGrowthDimension_eq_three
#print axioms Eden.normalizedLogSingularValues_periodic_le_unit
#print axioms Eden.spectrumInterpolation_mono_spectrum
#print axioms Eden.spectrumInterpolation_integer
#print axioms Eden.singularValueFunction_evolution_eq_exp_interpolation
#print axioms Eden.periodicIntegerGrowthValues_isGreatest
#print axioms Eden.periodicGlobalLogGrowth_eq
#print axioms Eden.tendsto_periodicGlobalLogGrowth_div
#print axioms Eden.periodicGlobalGrowthRate_eq
#print axioms Eden.periodicGlobalGrowthRate_table
#print axioms Eden.firstCircle_nonempty
#print axioms Eden.secondCircle_nonempty
#print axioms Eden.firstCircle_ne_firstCircle
#print axioms Eden.secondCircle_ne_secondCircle
#print axioms Eden.firstCircle_ne_secondCircle
#print axioms Eden.firstCircle_mem_geometricPeriodicOrbits
#print axioms Eden.secondCircle_mem_geometricPeriodicOrbits
#print axioms Eden.geometricPeriodicOrbits_eq
#print axioms Eden.geometricPeriodicOrbits_encard
#print axioms Eden.evolution_origin
#print axioms Eden.eq_zero_of_radii_and_fifth_zero
#print axioms Eden.vectorField_eq_zero_iff
#print axioms Eden.equilibriumSet_eq_singleton
#print axioms Eden.first_plane_return
#print axioms Eden.second_plane_return
#print axioms Eden.mem_positiveReturnSet_iff
#print axioms Eden.positiveReturnSet_subset_attractor
#print axioms Eden.periodicEquilibriumSet_eq_positiveReturnSet
#print axioms Eden.radiusEvolution_nonneg
#print axioms Eden.radiusEvolution_sq
#print axioms Eden.radiusEvolution_zero_time
#print axioms Eden.radiusEvolution_at_zero
#print axioms Eden.radiusEvolution_at_one
#print axioms Eden.radiusEvolution_at_sqrt_two
#print axioms Eden.radiusEvolution_pos
#print axioms Eden.radiusEvolution_mono
#print axioms Eden.radiusEvolution_le_max
#print axioms Eden.radiusEvolution_ge_sqrt_two
#print axioms Eden.hasDerivAt_radiusEvolution
#print axioms Eden.radiusEvolution_antitoneOn
#print axioms Eden.tendsto_radiusEvolution_of_lt_one
#print axioms Eden.tendsto_radiusEvolution_of_one_lt
#print axioms Eden.radius₁_evolution
#print axioms Eden.radius₂_evolution
#print axioms Eden.abs_fifth_evolution
#print axioms Eden.planarEvolution_zero_time
#print axioms Eden.hasDerivAt_planarEvolution
#print axioms Eden.contDiff_planarEvolution
#print axioms Eden.fderiv_planarEvolution_apply
#print axioms Eden.rotatePlane_inverse
#print axioms Eden.norm_rotatePlane
#print axioms Eden.planeRotation_apply
#print axioms Eden.planarDiagonal_apply
#print axioms Eden.fderiv_planarEvolution_radialFrame
#print axioms Eden.planarX_zero_time
#print axioms Eden.planarY_zero_time
#print axioms Eden.planarX_origin
#print axioms Eden.planarY_origin
#print axioms Eden.planar_radius_sq_of_pos
#print axioms Eden.planar_radius_sq
#print axioms Eden.hasDerivAt_planarX_of_pos
#print axioms Eden.hasDerivAt_planarX
#print axioms Eden.hasDerivAt_planarY_of_pos
#print axioms Eden.hasDerivAt_planarY
#print axioms Eden.planarMovingPerturbation_eq
#print axioms Eden.planarMovingPerturbation_zero_time
#print axioms Eden.hasDerivWithinAt_planarMovingPerturbation
#print axioms Eden.hasDerivAt_planarMovingPerturbation
#print axioms Eden.adjoint_planarDiagonal
#print axioms Eden.planarDiagonal_comp_self
#print axioms Eden.toMatrix_planarDiagonal
#print axioms Eden.roots_charpoly_planarDiagonal
#print axioms Eden.fderiv_planarEvolution_orthogonal_decomposition
#print axioms Eden.gram_fderiv_planarEvolution
#print axioms Eden.singularValues_fderiv_planarEvolution
#print axioms Eden.singularValues_fderiv_planarEvolution_integrals
#print axioms Eden.fderiv_planarEvolution_origin
#print axioms Eden.contDiff_planarVectorField
#print axioms Eden.fderiv_planarVectorField_apply
#print axioms Eden.toMatrix_fderiv_planarVectorField
#print axioms Eden.eval_vectorFieldPolynomial
#print axioms Eden.totalDegree_radiusPolynomial_le
#print axioms Eden.totalDegree_ratePolynomial_le
#print axioms Eden.totalDegree_vectorFieldPolynomial_le
#print axioms Eden.coeff_vectorFieldPolynomial_first
#print axioms Eden.totalDegree_vectorFieldPolynomial_first
#print axioms Eden.vectorFieldPolynomial_degree
#print axioms Eden.strictMono_squaredRadiusEvolution
#print axioms Eden.squaredRadiusEvolution_lt_zero_iff
#print axioms Eden.squaredRadiusEvolution_pos_iff
#print axioms Eden.squaredRadiusEvolution_lt_one_iff
#print axioms Eden.one_lt_squaredRadiusEvolution_iff
#print axioms Eden.squaredRadiusEvolution_le_two_iff
#print axioms Eden.squaredRadiusEvolution_lt_two_iff
#print axioms Eden.two_lt_squaredRadiusEvolution_iff
#print axioms Eden.squaredRadiusEvolution_le_initial
#print axioms Eden.squaredRadiusEvolution_le_max
#print axioms Eden.radialDiscriminant_pos_on_interval
#print axioms Eden.squaredRadiusEvolution_mem_interval
#print axioms Eden.tendsto_radialExponential
#print axioms Eden.tendsto_radialDiscriminant
#print axioms Eden.tendsto_squaredRadiusEvolution
#print axioms Eden.tendsto_squaredRadiusEvolution_of_lt_one
#print axioms Eden.tendsto_squaredRadiusEvolution_of_one_lt
#print axioms Eden.radialField_eq_zero_iff
#print axioms Eden.radialField_neg_below_one
#print axioms Eden.radialField_pos_between
#print axioms Eden.radialField_neg_above
#print axioms Eden.tendsto_radiusEvolution_one_iff
#print axioms Eden.isBounded_evolution_image_interval
#print axioms Eden.squaredRadiusEvolution_eq_self_iff
#print axioms Eden.radiusSq₁_eq_zero_iff
#print axioms Eden.radiusSq₂_eq_zero_iff
#print axioms Eden.stationary_radii_of_evolution_return
#print axioms Eden.fifth_eq_zero_of_evolution_return
#print axioms Eden.frequencyEvolution_torusPoint
#print axioms Eden.frequencyEvolution_add_on_torus
#print axioms Eden.frequency_torus_common_return
#print axioms Eden.frequency_torus_common_period
#print axioms Eden.rational_frequency_torus_period
#print axioms Eden.frequency_torus_not_equilibrium
#print axioms Eden.torus_subset_frequencyPeriodicSet
#print axioms Eden.frequency_periodic_asymptotic_isGreatest
#print axioms Eden.frequency_periodic_finiteTime_isGreatest
#print axioms Eden.exists_positive_rational_frequency
#print axioms Eden.exists_nearby_frequency_periodic_maximum
#print axioms Eden.real_subadditive_mul_add_le
#print axioms Eden.real_subadditive_div_le
#print axioms Eden.real_subadditive_eventually_div_lt
#print axioms Eden.tendsto_real_subadditive_div
#print axioms Eden.tendsto_div_time_of_hasDerivAt
#print axioms Eden.rotation_fixed_iff
#print axioms Eden.planar_return_cos_sin
#print axioms Eden.not_simultaneous_rotation_returns
#print axioms Eden.first_cos_eq_one_of_evolution_return
#print axioms Eden.second_cos_eq_one_of_evolution_return
#print axioms Eden.one_radius_zero_of_evolution_return
#print axioms Eden.torus_no_positive_return
#print axioms Eden.hasDerivAt_squaredRadiusEvolution_parameter
#print axioms Eden.continuous_radialDiscriminant_time
#print axioms Eden.hasDerivAt_amplitudeSq_of_discriminant_pos
#print axioms Eden.hasDerivAt_amplitudeSq
#print axioms Eden.planarAmplitude_pos
#print axioms Eden.planarAmplitude_sq
#print axioms Eden.planarAmplitude_zero_time
#print axioms Eden.hasDerivAt_planarAmplitude_of_pos
#print axioms Eden.hasDerivAt_planarAmplitude
#print axioms Eden.radialDiscriminant_pos
#print axioms Eden.sqrt_radialDiscriminant_pos
#print axioms Eden.amplitudeSq_pos
#print axioms Eden.mul_amplitudeSq_of_discriminant_pos
#print axioms Eden.mul_amplitudeSq
#print axioms Eden.squaredRadiusEvolution_nonneg
#print axioms Eden.radialDiscriminant_zero_time
#print axioms Eden.squaredRadiusEvolution_zero_time
#print axioms Eden.amplitudeSq_zero_time
#print axioms Eden.squaredRadiusEvolution_at_one
#print axioms Eden.radialDiscriminant_at_zero
#print axioms Eden.radialDiscriminant_at_two
#print axioms Eden.squaredRadiusEvolution_at_zero
#print axioms Eden.squaredRadiusEvolution_at_two
#print axioms Eden.amplitudeSq_at_zero
#print axioms Eden.hasDerivAt_squaredRadiusEvolution_of_discriminant_pos
#print axioms Eden.hasDerivAt_squaredRadiusEvolution
#print axioms Eden.prod_antitone_embedding_le
#print axioms Eden.isGreatest_selected_prod
#print axioms Eden.exists_equiv_of_multiset_eq
#print axioms Eden.orderEmbedding_fin_val_le
#print axioms Eden.sum_antitone_embedding_le
#print axioms Eden.isGreatest_selected_sum
#print axioms Eden.continuous_singularWeight
#print axioms Eden.singularWeight_eq_one
#print axioms Eden.singularWeight_eq_fraction
#print axioms Eden.singularWeight_eq_zero
#print axioms Eden.spectralProduct_interpolate
#print axioms Eden.spectralProduct_zero
#print axioms Eden.spectralProduct_top
#print axioms Eden.continuous_spectralProduct
#print axioms Eden.singularValueFunction_zero
#print axioms Eden.singularValueFunction_interpolate
#print axioms Eden.singularValueFunction_five
#print axioms Eden.continuous_singularValueFunction
#print axioms Eden.admissibleDimensions_nonempty
#print axioms Eden.isCompact_admissibleDimensions
#print axioms Eden.mapLyapunovDimension_isGreatest
#print axioms Eden.finiteTimeDimension_isGreatest
#print axioms Eden.finiteTimeDimension_mem_interval
#print axioms Eden.adjoint_diagonalLinear
#print axioms Eden.diagonalLinear_comp_self
#print axioms Eden.toMatrix_diagonalLinear
#print axioms Eden.charpoly_diagonalLinear
#print axioms Eden.roots_charpoly_diagonalLinear
#print axioms Eden.gram_orthogonalDiagonalMap
#print axioms Eden.roots_charpoly_gram_orthogonalDiagonalMap
#print axioms Eden.singularValues_orthogonalDiagonalMap
#print axioms Eden.singularValues_fderiv_evolution
#print axioms Eden.card_filter_eq_of_multiset_eq
#print axioms Eden.antitone_le_of_matched_le
#print axioms Eden.antitone_dist_le_of_matched_dist_le
#print axioms Eden.descending_antitone
#print axioms Eden.ofFn_descending
#print axioms Eden.multiset_descending
#print axioms Eden.lipschitzWith_descending
#print axioms Eden.continuous_descending
#print axioms Eden.tendsto_descending
#print axioms Eden.lyapunovExponent_eq_radiusPairSpectrum
#print axioms Eden.limitingSquaredRadius_cases
#print axioms Eden.limitingSquaredRadius_eq_one_iff
#print axioms Eden.descending_radiusPairSpectrum_swap
#print axioms Eden.lyapunovExponent_eq_of_limiting_radii
#print axioms Eden.descending_radiusPairSpectrum_zero_zero
#print axioms Eden.descending_radiusPairSpectrum_zero_one
#print axioms Eden.descending_radiusPairSpectrum_zero_two
#print axioms Eden.descending_radiusPairSpectrum_one_one
#print axioms Eden.descending_radiusPairSpectrum_one_two
#print axioms Eden.descending_radiusPairSpectrum_two_two
#print axioms Eden.planarAmplitude_at_zero
#print axioms Eden.radialAmplitude_at_zero
#print axioms Eden.planarAmplitude_at_one
#print axioms Eden.radialAmplitude_at_one
#print axioms Eden.planarAmplitude_at_two
#print axioms Eden.radialAmplitude_at_two
#print axioms Eden.planarDerivativeX_at_origin
#print axioms Eden.planarDerivativeY_at_origin
#print axioms Eden.derivativeFactors_at_origin
#print axioms Eden.derivativeFactors_on_torus
#print axioms Eden.squaredRadiusEvolution_surjOn
#print axioms Eden.planar_surjective_on_disc
#print axioms Eden.evolution_surjOn_attractor
#print axioms Eden.evolution_image_attractor
#print axioms Eden.torusPoint_mem
#print axioms Eden.exists_torusPoint_of_mem
#print axioms Eden.torusPoint_add_two_pi_first
#print axioms Eden.torusPoint_add_two_pi_second
#print axioms Eden.planarAmplitude_at_one_all
#print axioms Eden.evolution_torusPoint
#print axioms Eden.torus_invariant_all_real
#print axioms Eden.radialOrthonormalBasis_on_torus
#print axioms Eden.diagonalLinear_basisFun
#print axioms Eden.norm_fderiv_evolution_radialBasis
#print axioms Eden.norm_fderiv_torus_directions
#print axioms Eden.tendsto_torus_direction_growth
#print axioms Eden.torus_direction_rates_and_ordered_exponents
#print axioms Eden.dimH_attractor_lt_globalLyapunovDimension
#print axioms Eden.dimH_torus_lt_finiteTimeDimension
#print axioms Eden.evolution_eq_angularRotation_on_torus
#print axioms Eden.dist_evolution_torus
#print axioms Eden.torus_recurrence_dist
#print axioms Eden.torus_recurrence_nhds
#print axioms Eden.torus_recurrence_ambient_nhds
#print axioms Eden.torusEvolution_no_positive_return
#print axioms Eden.radial_excess_le
#print axioms Eden.dist_projection_evolution_sq_le
#print axioms Eden.infDist_evolution_attractor_sq_le
#print axioms Eden.tendsto_attractionBound
#print axioms Eden.radius₁_le_norm
#print axioms Eden.radius₂_le_norm
#print axioms Eden.bounded_set_radius_bounds
#print axioms Eden.attractor_uniformlyAttractsBounded
#print axioms Eden.uniformlyAttractsBounded_nonempty
#print axioms Eden.attractor_subset_of_uniformlyAttractsBounded
#print axioms Eden.attractor_isGlobalAttractor
#print axioms Eden.attractor_minimal
#print axioms Eden.empty_not_uniformlyAttractsBounded
#print axioms Eden.solution_unique_on_Icc
#print axioms Eden.continuousOn_evolution
#print axioms Eden.evolution_unique
#print axioms Eden.evolution_add
#print axioms Eden.hasDerivAt_q
#print axioms Eden.deriv_q
#print axioms Eden.radialRate_eq_q_add_deriv
#print axioms Eden.fderiv_planarVectorX_apply
#print axioms Eden.fderiv_planarVectorY_apply
#print axioms Eden.fderiv_vectorField_apply
#print axioms Eden.exp_fifth_lt_planar_bound
#print axioms Eden.derivativeFactors_planar_lower_bound
#print axioms Eden.derivativeFactors_fifth_lt_planar
#print axioms Eden.continuousOn_volumeDefect_integrand
#print axioms Eden.volumeDefect_integrand_nonneg
#print axioms Eden.log_singularValues_fderiv_evolution_prod_four
#print axioms Eden.radialDefect_nonneg
#print axioms Eden.radialDefect_at_one
#print axioms Eden.radialDefect_pos
#print axioms Eden.radialDefect_eq_zero_iff
#print axioms Eden.log_planar_factors
#print axioms Eden.planar_factors_product
#print axioms Eden.volumeDefect_eq_integral_evolution
#print axioms Eden.volumeDefect_nonneg
#print axioms Eden.volumeDefect_eq_zero_iff
#print axioms Eden.singularValues_fderiv_evolution_prod_four
#print axioms Eden.singularValues_fderiv_evolution_prod_four_le
#print axioms Eden.singularValues_fderiv_evolution_prod_four_eq_iff
